"use client";

import { cn } from "@/lib/utils";
import { AlertTriangle, CheckCircle, Car, Wrench } from "lucide-react";
import { z } from "zod";
import { motion } from "framer-motion";

/**
 * Schema for VehicleHero props - used by Tambo for generative UI
 */
export const vehicleHeroSchema = z.object({
  vehicleName: z.string().describe("Full name of the vehicle (e.g., '2015 Honda Civic')"),
  imageUrl: z.string().optional().describe("URL of the vehicle image from MCP"),
  status: z.enum(["safe", "critical", "warning"]).default("safe").describe("Current safety status of the issue"),
  issueDescription: z.string().optional().describe("Brief description of the detected issue"),
  confidence: z.number().min(0).max(100).optional().describe("AI confidence level in diagnosis (0-100)"),
});

export type VehicleHeroProps = z.infer<typeof vehicleHeroSchema>;

/**
 * VehicleHero Component
 * 
 * Displays vehicle information with status indicator.
 * This is the first component shown when a user describes their vehicle problem.
 * Generated by Tambo based on parsed vehicle intent.
 */
export function VehicleHero({
  vehicleName,
  imageUrl,
  status = "safe",
  issueDescription,
  confidence,
}: VehicleHeroProps) {
  const statusConfig = {
    safe: {
      icon: CheckCircle,
      color: "text-green-500",
      bg: "bg-green-500/10",
      border: "border-green-500/30",
      label: "Safe to Proceed",
    },
    warning: {
      icon: AlertTriangle,
      color: "text-yellow-500",
      bg: "bg-yellow-500/10",
      border: "border-yellow-500/30",
      label: "Proceed with Caution",
    },
    critical: {
      icon: AlertTriangle,
      color: "text-red-500",
      bg: "bg-red-500/10",
      border: "border-red-500/30",
      label: "Critical - Stop Driving",
    },
  };

  const config = statusConfig[status];
  const StatusIcon = config.icon;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className={cn(
        "rounded-2xl overflow-hidden border-2",
        config.border,
        "bg-gradient-to-br from-zinc-900/90 to-zinc-800/90",
        "shadow-2xl shadow-black/20"
      )}
    >
      {/* Vehicle Image Section */}
      <div className="relative h-48 bg-gradient-to-br from-zinc-800 to-zinc-900">
        {imageUrl ? (
          <img
            src={imageUrl}
            alt={vehicleName}
            className="w-full h-full object-cover opacity-80"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            <Car className="w-24 h-24 text-zinc-600" />
          </div>
        )}
        
        {/* Status Badge Overlay */}
        <div className="absolute top-4 right-4">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ delay: 0.3, type: "spring" }}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-full",
              config.bg,
              "backdrop-blur-sm border",
              config.border
            )}
          >
            <StatusIcon className={cn("w-5 h-5", config.color)} />
            <span className={cn("font-semibold text-sm", config.color)}>
              {config.label}
            </span>
          </motion.div>
        </div>

        {/* Gradient Overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-zinc-900 via-transparent to-transparent" />
      </div>

      {/* Vehicle Info Section */}
      <div className="p-6 space-y-4">
        <div className="flex items-start justify-between">
          <div>
            <h2 className="text-2xl font-bold text-white">{vehicleName}</h2>
            {issueDescription && (
              <p className="text-zinc-400 mt-1 flex items-center gap-2">
                <Wrench className="w-4 h-4" />
                {issueDescription}
              </p>
            )}
          </div>
          
          {confidence !== undefined && (
            <div className="text-right">
              <p className="text-xs text-zinc-500 uppercase tracking-wide">Confidence</p>
              <p className="text-lg font-bold text-white">{confidence}%</p>
            </div>
          )}
        </div>

        {/* Safety Warning for Critical Status */}
        {status === "critical" && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            className="bg-red-500/10 border border-red-500/30 rounded-lg p-4"
          >
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-6 h-6 text-red-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-red-400">Safety Warning</p>
                <p className="text-red-300/80 text-sm mt-1">
                  Park your vehicle safely before proceeding with any diagnostics.
                  Do not drive until the issue is resolved.
                </p>
              </div>
            </div>
          </motion.div>
        )}

        {/* Quick Actions */}
        <div className="flex gap-3 pt-2">
          <button className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-3 px-4 rounded-xl font-semibold transition-colors">
            Start Diagnosis
          </button>
          <button className="flex-1 bg-zinc-700 hover:bg-zinc-600 text-white py-3 px-4 rounded-xl font-semibold transition-colors">
            Get Help Now
          </button>
        </div>
      </div>
    </motion.div>
  );
}
